# Generated by Django 5.1.1 on 2025-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%M/%D/')),
                ('facebook', models.URLField(max_length=255)),
                ('linkedin', models.URLField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
